# insert into props (id, type, name) values
#                                    (0, 'class', 'Paladin'),
#                                    (1, 'class', 'Cleric'),
#                                    (2, 'class', 'Fighter'),
#                                    (3, 'class', 'Barbarian'),
#                                    (4, 'class', 'Monk'),
#                                    (5, 'class', 'Ranger'),
#                                    (6, 'class', 'Bard'),
#                                    (7, 'class', 'Druid'),
#                                    (8, 'class', 'Rogue'),
#                                    (9, 'race', 'Dwarf'),
#                                    (10, 'race', 'Half-orc'),
#                                    (11, 'race', 'Elf'),
#                                    (12, 'race', 'Halfling'),
#                                    (13, 'race', 'Human'),
#                                    (14, 'race', 'Dragonborn'),
#                                    (15, 'race', 'Gnome'),
#                                    (16, 'race', 'Half-elf'),
#                                    (17, 'race', 'Tiefling'),
#                                    (18, 'weapon', 'Dagger'),
#                                    (19, 'weapon', 'Greatclub'),
#                                    (20, 'weapon', 'Handaxe'),
#                                    (21, 'weapon', 'Javelin'),
#                                    (22, 'weapon', 'Light hammer'),
#                                    (23, 'weapon', 'Mace'),
#                                    (24, 'weapon', 'Sickle'),
#                                    (25, 'weapon', 'Spear'),
#                                    (26, 'weapon', 'Sword'),
#                                    (27, 'element', 'Stone, the primordial earth'),
#                                    (28, 'element', 'Water, the primordial sea'),
#                                    (29, 'element', 'Heat, the primordial flame'),
#                                    (30, 'element', 'Ether, the primordial space'),
#                                    (31, 'element', 'Light, the primordial day'),
#                                    (32, 'element', 'Dark, the primordial night'),
#                                    (33, 'element', 'Force, the primordial movement');